// node tests/dawg_pager.test.mjs — phase 2 of the private tab (2026-09-23): the "Group-chat calls" table
// inside the Recipe experiment card, and the new "Cell pager" card. Like dawg_experiment.test.mjs it runs
// the REAL inline code lifted out of dashboard.html between its /* <dawg-experiment> */ and
// /* <dawg-pager> */ markers (plus the page's own esc/fmtMD/fmtSpan/dexp helpers and dAmPm) in a node vm —
// no browser, no network, no real passphrase. The payload is the decrypted tests/fixtures/
// dawg_journal.enc.json (fixture passphrase "test-pass-only"), whose `experiment` and `radar_pager` blocks
// were generated by the Mac's own code (journal.dashboard_payload over a copy of the live state DB).
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import vm from "node:vm";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const DawgCrypto = require("../dawg_crypto.js");

const html = readFileSync(new URL("../dashboard.html", import.meta.url), "utf8");
const blob = JSON.parse(readFileSync(new URL("./fixtures/dawg_journal.enc.json", import.meta.url)));
const plain = JSON.parse(readFileSync(new URL("./fixtures/dawg_journal.plain.json", import.meta.url)));

function block(name) {
  const a = html.indexOf(`/* <${name}>`), b = html.indexOf(`/* </${name}> */`);
  assert.ok(a >= 0 && b > a, `markers for ${name} not found in dashboard.html`);
  return html.slice(a, b);
}
function line(prefix) {
  const l = html.split("\n").find(s => s.startsWith(prefix));
  assert.ok(l, `no line starting ${prefix}`);
  return l;
}
const els = {};
const errors = [];
const ctx = vm.createContext({
  console: { log: console.log, error: (...a) => errors.push(a.join(" ")) },
  dEl: (id) => (els[id] ||= { id, hidden: true, innerHTML: "" }),
});
vm.runInContext([line("const esc = "), line("const parseDate = "), line("const fmtMD = "), line("const fmtSpan = "),
  line("const dAmPm = "), block("dawg-experiment"), block("dawg-pager"),
  "globalThis.T = { dexpHTML, dexpChatHTML, renderDawgExperiment, renderDawgPager, dpgHTML, dpgGateRows, dpgTime, dpgLead, dpgOutcome, DPG_GATES, esc, fmtMD };",
].join("\n"), ctx, { filename: "dashboard.html#inline" });
const T = ctx.T;
const clone = (o) => JSON.parse(JSON.stringify(o));
const noLeak = (h, what) => assert.ok(!/undefined|NaN|\bnull\b|\[object Object\]/.test(h), `${what}: leaked undefined/NaN/null`);
let n = 0;
const test = (name, fn) => { try { fn(); n++; } catch (e) { e.message = `${name}: ${e.message}`; throw e; } };

// ---------------------------------------------------------------- page wiring
test("pager section sits right after the experiment card, in the lock/hide list, rendered in order", () => {
  assert.match(html, /id="dawgExperiment" aria-labelledby="dawgExperiment-h" hidden><\/section>\s*<section class="card" id="dawgPager" aria-labelledby="dawgPager-h" hidden><\/section>/);
  assert.match(html, /const DAWG_CARDS = \["dawgVerdict", "dawgExperiment", "dawgPager",/);
  assert.match(html, /renderDawgExperiment\(d\); renderDawgPager\(d\);/);
});

// ---------------------------------------------------------------- the fixture, through the real decrypt
const data = await DawgCrypto.decrypt(blob, "test-pass-only");
assert.deepEqual(data, plain);
const X = data.experiment, C = X.chat, P = data.radar_pager;

test("fixture carries the phase-2 contract (Mac-generated shapes)", () => {
  assert.ok(C && typeof C === "object", "experiment.chat");
  assert.equal(typeof C.note, "string");
  assert.ok(Array.isArray(C.metrics) && C.metrics.length >= 5);
  const keys = C.metrics.map(m => m.key);
  for (const k of ["chat_high_mae_edge", "chat_brier_edge", "chat_window_hit_short", "chat_amt_light_bias", "chat_calls"])
    assert.ok(keys.includes(k), `chat metric ${k}`);
  for (const m of C.metrics) {
    for (const k of ["key", "label", "unit", "better", "v1", "v2", "delta", "status"]) assert.ok(k in m, `${m.key}.${k}`);
    assert.ok(["improved", "worse", "same", "insufficient"].includes(m.status), m.status);
    assert.ok(!m.headline, `${m.key} must never be a headline`);
  }
  assert.ok(P && typeof P === "object", "radar_pager");
  for (const k of ["since", "pages", "tally", "decided", "hit_rate", "recent", "verdicts_30d", "rule", "note"]) assert.ok(k in P, `radar_pager.${k}`);
  for (const k of ["hit", "miss", "faded", "open"]) assert.equal(typeof P.tally[k], "number", `tally.${k}`);
  assert.ok(Array.isArray(P.recent) && P.recent.length >= 1 && P.recent.length <= 15);
  for (const r of P.recent) for (const k of ["date", "time_local", "town", "dbz", "outcome", "lead_min"]) assert.ok(k in r, `recent.${k}`);
  assert.equal(P.decided, P.tally.hit + P.tally.miss + P.tally.faded);
});

// ---------------------------------------------------------------- F1: chat table inside the experiment card
test("chat table renders after the morning table, before the rule, from the fixture", () => {
  T.renderDawgExperiment(data);
  const el = els.dawgExperiment, h = el.innerHTML;
  assert.equal(el.hidden, false);
  const iMorning = h.indexOf("metric by metric"), iChat = h.indexOf("Group-chat calls · tracked, not in the verdict"), iRule = h.indexOf("<b>The rule.</b>");
  assert.ok(iMorning > 0 && iChat > iMorning && iRule > iChat, "order: morning table, chat, rule");
  assert.ok(h.includes(T.esc(C.note)), "chat note");
  assert.equal((h.match(/<table class="dawg-table dexp-table">/g) || []).length, 2, "two tables, same format");
  const chat = h.slice(iChat, iRule);
  for (const m of C.metrics) assert.ok(chat.includes(T.esc(m.label || m.key)), `chat row ${m.key}`);
  assert.ok(!/class="hl"/.test(chat), "no chat row is emphasized as a headline");
  assert.ok(!/>Headline</.test(chat), "no chat row is labelled Headline");
  assert.equal((chat.match(/<tr><td>/g) || []).length, C.metrics.length);
  // thresholds: a chat_ key borrows its morning twin's pre-registered line
  assert.match(chat, /counts past ±0\.25°F/);
  assert.match(chat, /counts past ±0\.010/);
  assert.match(chat, /counts past ±10\.0 pts/);
  assert.match(chat, /counts past ±0\.030&quot;/);
  noLeak(h, "experiment card with chat");
});

test("chat cells: v1 side is the Mac's live numbers, formatted like the morning table", () => {
  const h = els.dawgExperiment.innerHTML, chat = h.slice(h.indexOf("Group-chat calls"));
  const hm = C.metrics.find(m => m.key === "chat_high_mae_edge");
  const s = hm.v1;
  const f = (v) => (v > 0 ? "+" : "") + v.toFixed(2);
  assert.ok(chat.includes(`${f(s.value)}°F<span class="sub">n=${s.n}</span>`), "chat high edge v1 cell");
  const calls = C.metrics.find(m => m.key === "chat_calls");
  assert.ok(chat.includes(`>${calls.v1.value}<span class="sub">n=${calls.v1.n}</span>`), "chat_calls count cell");
});

test("chat absent / null / junk renders nothing; empty metrics say so", () => {
  for (const c of [undefined, null, "x", 3]) {
    const d = clone(data);
    if (c === undefined) delete d.experiment.chat; else d.experiment.chat = c;
    T.renderDawgExperiment(d);
    assert.equal(els.dawgExperiment.hidden, false, "morning card still renders");
    assert.ok(!/Group-chat calls/.test(els.dawgExperiment.innerHTML), `chat=${c}`);
    assert.equal((els.dawgExperiment.innerHTML.match(/dexp-table/g) || []).length, 1);
  }
  const d = clone(data); d.experiment.chat = { note: "n", metrics: [] };
  T.renderDawgExperiment(d);
  assert.match(els.dawgExperiment.innerHTML, /Group-chat calls[\s\S]*No paired chat calls yet/);
  // a throwing chat field hides only the experiment card (the pager is a separate card)
  const e = clone(data); Object.defineProperty(e.experiment, "chat", { get() { throw new Error("chat-boom"); }, enumerable: true });
  T.renderDawgExperiment(e);
  assert.equal(els.dawgExperiment.hidden, true);
  assert.ok(errors.some(x => /chat-boom/.test(x)));
});

// ---------------------------------------------------------------- F2: the cell pager card
test("pager card renders every contract section from the fixture", () => {
  T.renderDawgPager(data);
  const el = els.dawgPager, h = el.innerHTML;
  assert.equal(el.hidden, false);
  assert.match(h, /<h2 id="dawgPager-h">Cell pager · do 'cell inbound' texts pay off\?<\/h2>/);
  assert.ok(h.includes(`since ${T.fmtMD(P.since)}`));
  const pct = P.hit_rate == null ? "" : `<span class="pct">(${Math.round(P.hit_rate * 100)}%)</span>`;
  assert.ok(h.includes(`<span class="v">${P.tally.hit} of ${P.decided}</span>${pct}`), "big measured hit rate");
  for (const [k, cls] of [["hit", "ok"], ["miss", "miss"], ["faded", "pend"], ["open", "pend"]])
    assert.ok(h.includes(`<span class="dawg-pill ${P.tally[k] ? cls : "pend"}">${P.tally[k]} ${k}</span>`), `tally pill ${k}`);
  assert.match(h, /<th>Date<\/th><th>Time<\/th><th>Near<\/th><th class="num">dBZ<\/th><th>Outcome<\/th><th class="num">Lead<\/th>/);
  assert.equal((h.match(/<tr><td>/g) || []).length, P.recent.length);
  for (const r of P.recent) {
    assert.ok(h.includes(`<td>${T.fmtMD(r.date)}</td><td>${T.dpgTime(r.time_local)}</td><td>${r.town ? T.esc(r.town) : "—"}</td>`), `row ${r.date} ${r.time_local}`);
  }
  assert.match(h, /What the gates held back · last 30 days/);
  assert.ok(h.includes(T.esc(P.rule)), "rule");
  assert.ok(h.includes(T.esc(P.note)), "note");
  assert.ok(h.indexOf("dpg-table") < h.indexOf("What the gates held back"), "recent before gates");
  assert.match(h, /<div class="dawg-wrap"><table class="dawg-table dpg-table">/);   // phone scroll wrapper
  noLeak(h, "pager card");
});

test("pager: the Mac's real latch (09-20 Bogart hit) rides the fixture", () => {
  const h = els.dawgPager.innerHTML;
  const real = P.recent.find(r => r.date === "2026-09-20");
  assert.ok(real, "the one live page");
  assert.equal(real.outcome, "hit");
  assert.equal(real.town, "Bogart");
  assert.match(h, /Sep 20<\/td><td>[^<]+<\/td><td>Bogart<\/td>\s*<td class="num">45<\/td><td><span class="dawg-pill ok">hit<\/span>/);
});

test("gate tally: grouped, plain English, biggest first", () => {
  const rows = T.dpgGateRows(P.verdicts_30d);
  const h = els.dawgPager.innerHTML;
  const total = Object.values(P.verdicts_30d).reduce((a, b) => a + b, 0);
  assert.equal(rows.reduce((a, r) => a + r[1], 0), total, "grouping keeps every count");
  for (const [k, c] of rows) assert.ok(h.includes(`<b>${c}</b><span>${T.esc(T.DPG_GATES[k] || k)}`), `gate ${k}`);
  for (let i = 1; i < rows.length; i++) assert.ok(rows[i - 1][1] >= rows[i][1], "sorted by count");
  assert.deepEqual(JSON.parse(JSON.stringify(T.dpgGateRows({ "ghost-gated(grid=None)": 2, "ghost-gated(grid=38.5)": 3, paged: 1, "tracked-wide": 4, weird: 0 }))),
                   [["ghost-gated", 5], ["tracked-wide", 4], ["paged", 1]]);
  assert.deepEqual(JSON.parse(JSON.stringify(T.dpgGateRows(null))), []);
});

test("pager: no decided pages, empty lists, open-only", () => {
  const d = clone(data);
  Object.assign(d.radar_pager, { pages: 2, tally: { hit: 0, miss: 0, faded: 0, open: 2 }, decided: 0, hit_rate: null, verdicts_30d: {}, recent: [] });
  T.renderDawgPager(d);
  const h = els.dawgPager.innerHTML;
  assert.match(h, /<span class="v none">no decided pages yet<\/span><span class="lbl">2 pages sent, still being scored<\/span>/);
  assert.match(h, /<span class="dawg-pill pend">2 open<\/span>/);
  assert.match(h, /<span class="dawg-pill pend">0 hit<\/span><span class="dawg-pill pend">0 miss<\/span>/);   // zeros read muted
  const w = clone(data);
  Object.assign(w.radar_pager, { tally: { hit: 3, miss: 2, faded: 1, open: 1 }, decided: 6, hit_rate: 0.5 });
  T.renderDawgPager(w);
  assert.match(els.dawgPager.innerHTML, /<span class="v">3 of 6<\/span><span class="pct">\(50%\)<\/span>/);
  assert.match(els.dawgPager.innerHTML, /<span class="dawg-pill ok">3 hit<\/span><span class="dawg-pill miss">2 miss<\/span><span class="dawg-pill pend">1 faded<\/span><span class="dawg-pill pend">1 open<\/span>/);
  T.renderDawgPager(d);
  assert.match(h, /No pages yet — the pager only texts/);
  assert.match(h, /No threat-grade cells in the last 30 days\./);
  assert.ok(!/\(\d+%\)/.test(h), "no percentage without decided pages");
  const z = clone(data);
  Object.assign(z.radar_pager, { since: null, pages: 0, tally: { hit: 0, miss: 0, faded: 0, open: 0 }, decided: 0, hit_rate: null, recent: [] });
  T.renderDawgPager(z);
  assert.match(els.dawgPager.innerHTML, /no pages sent yet/);
  assert.ok(!/since /.test(els.dawgPager.innerHTML.split("</h2>")[1].split("</div>")[0]), "no since meta");
});

test("pager absent / null / junk hides the card; a throwing field hides only this card", () => {
  for (const d of [{}, { radar_pager: null }, { radar_pager: "x" }, null, undefined]) {
    els.dawgPager = { id: "dawgPager", hidden: false, innerHTML: "stale" };
    T.renderDawgPager(d);
    assert.equal(els.dawgPager.hidden, true);
    assert.equal(els.dawgPager.innerHTML, "");
  }
  T.renderDawgPager({ radar_pager: {} });                      // minimal object: renders, sensible empties
  assert.equal(els.dawgPager.hidden, false);
  assert.match(els.dawgPager.innerHTML, /no decided pages yet/);
  noLeak(els.dawgPager.innerHTML, "minimal pager");
  // junk-typed fields degrade to dashes, never "undefined"/"[object Object]"
  T.renderDawgPager({ radar_pager: { tally: "x", recent: [null, 3, { date: "2026-09-21", time_local: 1405, town: null, dbz: "abc", outcome: null, lead_min: "?" }], rule: { a: 1 }, note: 7, verdicts_30d: [1, 2] } });
  const h = els.dawgPager.innerHTML;
  assert.match(h, /<td>Sep 21<\/td><td>—<\/td><td>—<\/td>\s*<td class="num">—<\/td><td><span class="dawg-pill pend">open<\/span><\/td><td class="num">—<\/td>/);
  noLeak(h, "junk pager");
  T.renderDawgPager({ radar_pager: { since: "soon", recent: [{ date: "yesterday", time_local: "9:05", outcome: "hit" }] } });
  assert.ok(!/Invalid Date|since /.test(els.dawgPager.innerHTML), "junk dates never print");
  assert.match(els.dawgPager.innerHTML, /<tr><td>—<\/td><td>9:05 AM<\/td>/);
  // the experiment card is untouched when the pager throws
  T.renderDawgExperiment(data);
  const before = els.dawgExperiment.innerHTML;
  T.renderDawgPager({ radar_pager: { get recent() { throw new Error("pager-boom"); } } });
  assert.equal(els.dawgPager.hidden, true);
  assert.equal(els.dawgPager.innerHTML, "");
  assert.ok(errors.some(e => /pager-boom/.test(e)));
  assert.equal(els.dawgExperiment.innerHTML, before);
  assert.equal(els.dawgExperiment.hidden, false);
});

test("pager: everything from the payload is escaped", () => {
  const d = clone(data);
  d.radar_pager.recent[0].town = "<img src=x onerror=alert(1)>";
  d.radar_pager.rule = "<script>x</script>";
  d.radar_pager.verdicts_30d = { "<b>odd</b>": 2 };
  d.radar_pager.tally.weird = 1;
  d.radar_pager.recent[0].outcome = '"><i>';
  T.renderDawgPager(d);
  const h = els.dawgPager.innerHTML;
  assert.ok(!h.includes("<img") && !h.includes("<script") && !h.includes("<b>odd") && !h.includes('"><i>'));
  assert.ok(h.includes("&lt;script&gt;x&lt;/script&gt;"));
  assert.match(h, /<span class="dawg-pill pend">1 weird<\/span>/);           // unknown tally keys still shown
});

test("pager helpers", () => {
  assert.equal(T.dpgTime("14:05"), "2:05 PM");
  assert.equal(T.dpgTime("07:00"), "7 AM");
  assert.equal(T.dpgTime("00:30"), "12:30 AM");
  assert.equal(T.dpgTime("25:00"), "—");
  assert.equal(T.dpgTime(""), "—");
  assert.equal(T.dpgTime(null), "—");
  assert.equal(T.dpgLead(22), "22 min");
  assert.equal(T.dpgLead(0), "0 min");
  assert.equal(T.dpgLead(-4), "4 min late");
  assert.equal(T.dpgLead(null), "—");
  assert.equal(T.dpgLead("x"), "—");
  assert.match(T.dpgOutcome("miss"), /dawg-pill miss">miss/);
  assert.match(T.dpgOutcome("faded"), /dawg-pill pend">faded/);
  assert.match(T.dpgOutcome(null), /dawg-pill pend">open/);
});

console.log(`dawg_pager: ${n} render checks OK (chat table + cell pager card, fixture ${blob.plain_bytes} bytes)`);
